### ISSUE TITLE
need a way to wait until containers are fully ready

### ISSUE THREAD

**Issue by stantonk** [dkanejs/docker-compose-maven-plugin#13]
I love how simple & lightweight this plugin is -- it's almost exactly what I am looking for.

The one problem you run into pretty quickly when leveraging docker for test dependencies is they need to be fully started up before you can run your tests (race conditions).

I think the simplest solution is some way to specify healthchecks that cause the next maven phase to wait for them to pass, e.g. https://dmp.fabric8.io/#start-wait

I would love to use fabric8 but we're not ready to use docker for our services/apps, just for local and CI testing -- which means dockerizing the application just to run the tests doesn't make a ton of sense.

**Comment by dkanejs** [comment]
@stantonk thanks 👍 and I like the idea of a healthcheck/wait feature.

To keep it simple & lightweight, leveraging the [healthcheck in the docker-compose file](https://docs.docker.com/compose/compose-file/#healthcheck) for this purpose would be a good starter. 

So basically as described, waiting until the docker-compose health check has passed before proceeding to the next phase.

**Comment by stantonk** [comment]
@dkanejs aye. I tried using healthchecks and I couldn't get it to work (I was using `depends_on`). Then I found this:

<img width="828" alt="screenshot 2017-10-22 14 41 46" src="https://user-images.githubusercontent.com/519545/31865614-38b40676-b737-11e7-8a8d-7c2ac6da7b0d.png">

I may have been doing something improperly though, I was in a rush. I was definitely using version 3 of docker-compose format.

**Comment by joachimbjorklund** [comment]
I did recently implement a health-checker actually. It is simple, and based on checking url's for the text OK.

Our services publishes an endpoint that returns OK when it is ready to serve. And services that depends on such service just polls it until ok or bails out.

I did put it in a repo, check it out if it is usable for your needs: https://github.com/joachimbjorklund/jibe-tools-healthcheck

**Comment by dkanejs** [comment]
Hmm, doesn't appear a way to do this with compose without using a wrapper script which is a bit rubbish, but I think we can do it by: 

1. Waiting until all health checks are healthy before progressing
2. User providing a timeout as not to wait forever

Any input or feedback would be appreciated.

**Comment by ShahinKordasti** [comment]
I would :+1:  this as I am currently querying my services as a precondition in the tests to see that they are running. Have a look at the wait functionality of http://dmp.fabric8.io/#start-wait for ideas.

**Comment by dkanejs** [comment]
Ah nice, this looks like a nice solution for those who require the wait  👍 

(I want to keep this project nice and light, I feel those who require a wait feature would be better contributing and using your project @slem1 )

**Comment by NXSNXS** [comment]
This solution requires that the port is duplicated in both the compose file and the pom.
