### ISSUE TITLE
need remove images created by docker-compose 

### ISSUE THREAD

**Issue by ikkiwar** [dkanejs/docker-compose-maven-plugin#22]
would be a great help when plugin download containers then delete the images created or have an option to do so

**Comment by dkanejs** [comment]
Just to be clear you want the `--rmi` option of `docker-compose down` (documented [here](https://docs.docker.com/compose/reference/down/)) to be available?

**Comment by dkanejs** [comment]
Going out in next release 🎉

**Comment by ikkiwar** [comment]
thanks man this plugin is really great!!
