### ISSUE TITLE
docker-compose logs

### ISSUE THREAD

**Issue by ShahinKordasti** [dkanejs/docker-compose-maven-plugin#31]
During running integration tests I find it very useful to be able to see the logs. Currently I am running a separate script which runs: `docker-compose logs -f -t`. It would be useful if this plugin could do something similar after doing the compose:up in detached mode.

E.g.:
```
<execution>
    <id>up</id>
    <phase>pre-integration-test</phase>
    <goals>
        <goal>up</goal>
    </goals>
    <configuration>
        <detachedMode>true</detachedMode>
        <log>true</log>
        <composeFile>...</composeFile>
    </configuration>
</execution>
```

**Comment by fabienmifsud** [comment]
Hi, has this enhancement been released ?

**Comment by dkanejs** [comment]
Hi @fabienmifsud,

In short, no. The logs are not available to the plugin when running in detached mode as the `docker-compose` process is not attached to the Maven process.

You can look at the container logs using the standard `docker-compose logs` method when running in detached mode.

**Comment by fabienmifsud** [comment]
Ok, thanks for the answer :)
