### ISSUE TITLE
support -p command for instantiating image with project name

### ISSUE THREAD

**Issue by jagdeepjain** [dkanejs/docker-compose-maven-plugin#36]
I am need of starting the container with the `-p` option.
`$ docker-compose -p projectName up -d`

This will help in having different images with single docker-compose file.

Needed support for `-p` option for docker-compose

**Comment by dkanejs** [comment]
Working on this at the moment, should be out in the next release 👍

**Comment by dkanejs** [comment]
work done in #47

**Comment by jagdeepjain** [comment]
Thanks @dkanejs this is useful
