### ISSUE TITLE
Add support for docker-compose stop

### ISSUE THREAD

**Issue by zsenyeg** [dkanejs/docker-compose-maven-plugin#53]
Hey,

Thx, for this nice and easy-to-use plugin.

It would be very nice to use docker-compose stop command by this plugin. The main reason is i use oracle 12.1 docker image for integration testing, and docker-compose up can be very slow with this oracle image. There are other solutions for example pre installed oracle docker image, but docker-compose stop would be much easier.

Cheers,
zsenyeg

**Comment by dkanejs** [comment]
Hey @zsenyeg,

Thanks 😄 

Yeah I can see the use case for this, let me take a look and see what I can do 👍

**Comment by scormaq** [comment]
Hi @dkanejs, tnx for great plugin.
Is it possible to add support for `docker-compose pull` too? It would be handy sometimes just to pull images without starting services by `up` command.

**Comment by dkanejs** [comment]
@scormaq I've created #61 with your idea 👍

**Comment by dkanejs** [comment]
Fixed in #67 and released in #71
