### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by gabrielbauman** [dkanejs/docker-compose-maven-plugin#59]
Hey @dkanejs,

I sent in a few pull requests a while back, but it seems you're busy. Was just wondering if you'd like some maintainer assistance for this project? I'd be happy to do triage, get PRs into shape and/or make releases.

Let me know!

**Comment by dkanejs** [comment]
Hey @gabrielbauman,

>I sent in a few pull requests a while back, but it seems you're busy

Yeah thanks for the PRs 👍 just responding to them now, much appreciated. 

>Was just wondering if you'd like some maintainer assistance for this project? 

Yeah, if you're keen that sounds grand 😄Let me get this organised. 

I really need to pipeline the release process tbh, think i'll get this done this weekend (_I currently sign the jars with my hardware key but I will figure something new out_)

Will get back in touch shortly!

**Comment by dkanejs** [comment]
Done 👍 (For now I'll still handle the releases until I automate.)
