### ISSUE TITLE
Testing & 2 Setups

### ISSUE THREAD

**Issue by stefnats** [dkanejs/docker-compose-maven-plugin#76]
For processing integration tests and running queries against some small test database instances, it would be neat to have the docker-compose services up during test and down after that.

Is this possible? I didn't find it in the documentation

**Comment by dkanejs** [comment]
Hey @stefnats, 

That's the purpose of this plugin as you can bind it to the various phases: https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference

So best to bind:
- `up` goal to to `pre-integration-test`
- `down` goal to `post-integration-test`

What does your configuration look like right now?
