### ISSUE TITLE
'service feature' is not supported on 'docker-compose down' goal

### ISSUE THREAD

**Issue by IomHamstro** [dkanejs/docker-compose-maven-plugin#77]
There is new feature with property 'services' in configuration, which allow to execute only specified services. 
For command 'up' and 'stop' it works correctly. But for command 'down' I did not find it in 
DockerComposeDownMojo.java . 
Is it bug or feature?

**Comment by dkanejs** [comment]
Hey @IomHamstro,

It's not supported by `docker-compose` itself: 

https://github.com/docker/compose/issues/3228#issuecomment-202826652
